# Generated by Django 3.1.4 on 2021-04-16 15:08

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listing',
            name='start_date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
