# Generated by Django 3.1.4 on 2021-04-16 16:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0002_auto_20210416_1508'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='listing',
            name='start_date',
        ),
    ]
