# Generated by Django 3.1.4 on 2021-04-21 20:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0006_auto_20210420_0102'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='watchlist',
            name='items',
        ),
        migrations.AddField(
            model_name='watchlist',
            name='items',
            field=models.ForeignKey(blank='True', null='Ture', on_delete=django.db.models.deletion.CASCADE, related_name='item_w', to='auctions.listing'),
            preserve_default='Ture',
        ),
    ]
