# Generated by Django 3.1.4 on 2021-04-26 15:47

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0008_auto_20210424_1626'),
    ]

    operations = [
        migrations.AddField(
            model_name='listing',
            name='end_date',
            field=models.DateTimeField(default=datetime.datetime(2021, 4, 27, 15, 47, 16, 905719, tzinfo=utc)),
        ),
        migrations.AddField(
            model_name='listing',
            name='start_date',
            field=models.DateTimeField(default=datetime.datetime(2021, 4, 26, 15, 47, 16, 905693, tzinfo=utc)),
        ),
    ]
