# Generated by Django 3.1.4 on 2021-04-26 15:57

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0009_auto_20210426_1547'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listing',
            name='end_date',
            field=models.DateTimeField(default=datetime.datetime(2021, 5, 3, 15, 57, 51, 14802, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='listing',
            name='start_date',
            field=models.DateTimeField(default=datetime.datetime(2021, 4, 26, 15, 57, 51, 14776, tzinfo=utc)),
        ),
    ]
