# Generated by Django 3.1.4 on 2021-04-26 20:07

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0010_auto_20210426_1557'),
    ]

    operations = [
        migrations.AddField(
            model_name='listing',
            name='current_bid',
            field=models.DecimalField(decimal_places=2, default='0.00', max_digits=10),
        ),
        migrations.AlterField(
            model_name='listing',
            name='end_date',
            field=models.DateTimeField(default=datetime.datetime(2021, 5, 3, 20, 7, 29, 580697, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='listing',
            name='start_date',
            field=models.DateTimeField(default=datetime.datetime(2021, 4, 26, 20, 7, 29, 580671, tzinfo=utc)),
        ),
    ]
