# Generated by Django 3.1.4 on 2021-04-27 14:43

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0011_auto_20210426_2007'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listing',
            name='end_date',
            field=models.DateTimeField(default=datetime.datetime(2021, 4, 27, 14, 43, 30, 894277, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='listing',
            name='start_date',
            field=models.DateTimeField(default=datetime.datetime(2021, 4, 27, 14, 43, 30, 894251, tzinfo=utc)),
        ),
    ]
