# Generated by Django 3.1.4 on 2021-04-27 16:43

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0012_auto_20210427_1443'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listing',
            name='current_bid',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
        migrations.AlterField(
            model_name='listing',
            name='end_date',
            field=models.DateTimeField(default=datetime.datetime(2021, 4, 27, 16, 43, 17, 61673, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='listing',
            name='start_date',
            field=models.DateTimeField(default=datetime.datetime(2021, 4, 27, 16, 43, 17, 61646, tzinfo=utc)),
        ),
    ]
