# Generated by Django 3.1.4 on 2021-04-27 21:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0014_auto_20210427_2057'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='listing',
            name='start_date',
        ),
        migrations.RemoveField(
            model_name='listing',
            name='winner',
        ),
    ]
