# Generated by Django 3.1.4 on 2021-04-27 21:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0016_auto_20210427_2141'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='listing',
            name='end_date',
        ),
        migrations.RemoveField(
            model_name='listing',
            name='start_date',
        ),
    ]
